#!groovy
podTemplate(
  label: "skopeo-pod",
  cloud: "openshift",
  inheritFrom: "maven",
  containers: [
    containerTemplate(
      name: "jnlp",
      image: "docker-registry.default.svc:5000/${GUID}-jenkins/jenkins-agent-appdev",
      resourceRequestMemory: "2Gi",
      resourceLimitMemory: "2Gi",
      resourceRequestCpu: "2",
      resourceLimitCpu: "2"
    )
  ]
) {
  node('skopeo-pod') {
    // Define Maven Command to point to the correct
    // settings for our Nexus installation
    def mvnCmd = "mvn -s ../nexus_settings.xml"

    // Other vars
    def sonar_url = "http://sonarqube-gpte-hw-cicd.apps.na311.openshift.opentlc.com"
    def sonar_svc = "http://sonarqube.gpte-hw-cicd.svc.cluster.local:9000"
    def nexus_url = "http://nexus3.gpte-hw-cicd.svc.cluster.local:8081/repository/releases"
    def nexus_registry = "nexus3-registry.gpte-hw-cicd.svc.cluster.local:5000"
    def nexus_registry_svc = "https://nexus3-registry.gpte-hw-cicd.svc.cluster.local:5000"

    // Set project names
    def devProject = "${GUID}-tasks-dev"
    def prodProject = "${GUID}-tasks-prod"

    // Checkout Source Code.
    stage('Checkout Source') {
      checkout scm
    }

    // Build the Tasks Service
    dir('openshift-tasks') {
      // The following variables need to be defined at the top level
      // and not inside the scope of a stage - otherwise they would not
      // be accessible from other stages.
      // Extract version from the pom.xml
      // def version = getVersionFromPom("pom.xml")
      def pom = readMavenPom file: 'pom.xml'
      def version = pom.version

      // TBD Set the tag for the development image: version + build number
      def devTag  = "${version}-" + currentBuild.number
      // Set the tag for the production image: version
      def prodTag = "${version}-"

      // Using Maven build the war file
      // Do not run tests in this step
      stage('Build war') {
        echo "Building version ${devTag}"

        // TBD: Execute Maven Build
	sh "${mvnCmd} clean package -DskipTests=true"
      }

      // TBD: The next two stages should run in parallel

      // Using Maven run the unit tests
      stage('Code & Unit Tests') {
	parallel 'unitTests': {
	  stage ('Unit Tests') {
            echo "Running Unit Tests"

            // TBD: Execute Unit Tests
	    sh "${mvnCmd} test"
	    //step([$class: 'JUnitResultArchiver', testResults: '**/target/surefire-reports/TEST-*.xml'])
	  }
        },
	'codeAnalysis': {
          // Using Maven to call SonarQube for Code Analysis
          stage('Code Analysis') {
            echo "Running Code Analysis"

            // TBD: Execute Sonarqube Tests
  	    sh "${mvnCmd} sonar:sonar -Dsonar.host.url=${sonar_svc} -Dsonar.projectName=${JOB_BASE_NAME} -Dsonar.projectVersion=${devTag}"
	  }
        },
	failFast: true
      }

      // Publish the built war file to Nexus
      stage('Publish to Nexus') {
        echo "Publish to Nexus"

        // TBD: Publish to Nexus
	sh "${mvnCmd} deploy -DskipTests=true -DaltDeploymentRepository=nexus::default::${nexus_url}"
      }

      // Build the OpenShift Image in OpenShift and tag it.
      stage('Build and Tag OpenShift Image') {
        echo "Building OpenShift container image tasks:${devTag}"
	script {
          // TBD: Build Image, tag Image
    	  openshift.withCluster() {
            openshift.withProject("${devProject}") {
	      // build inside project
	      openshift.selector("bc", "tasks").startBuild("--from-file=./target/openshift-tasks.war", "--wait=true")
	      // tag image
	      openshift.tag("tasks:latest", "tasks:${devTag}")
	    }
   	  }
        }
      }

      // Deploy the built image to the Development Environment.
      stage('Deploy to Dev') {
        echo "Deploying container image to Development Project"
	script {
          // TBD: Deploy to development Project
          //      Set Image, Set VERSION
          //      Make sure the application is running and ready before proceeding
	  openshift.withCluster() {
            openshift.withProject("${devProject}") {
	      openshift.set("image", "dc/tasks", "tasks=docker-registry.default.svc:5000/${devProject}/tasks:${devTag}")
              openshift.selector('configmap', 'tasks-config').delete()
	      def configmap = openshift.create('configmap', 'tasks-config', '--from-file=./configuration/application-users.properties', '--from-file=./configuration/application-roles.properties' )
	      openshift.set("env dc/tasks VERSION='${devTag} (tasks-dev)' -n ${GUID}-tasks-dev")
	      // Deploy the development application.
              openshift.selector("dc", "tasks").rollout().latest();

              // Wait for application to be deployed
              def dc = openshift.selector("dc", "tasks").object()
              def dc_version = dc.status.latestVersion
              def rc = openshift.selector("rc", "tasks-${dc_version}").object()
              echo "Waiting for ReplicationController tasks-${dc_version} to be ready"
              while (rc.spec.replicas != rc.status.readyReplicas) {
                sleep 5
                rc = openshift.selector("rc", "tasks-${dc_version}").object()
              }
	    }
	  }
        }
      }

      // Copy Image to Nexus container registry
      stage('Copy Image to Nexus container registry') {
        echo "Copy image to Nexus container registry"
        script {
          // TBD: Copy image to Nexus container registry
	  sh "skopeo copy \
	  --src-tls-verify=false --dest-tls-verify=false \
	  --src-creds openshift:\$(oc whoami -t) \
	  --dest-creds admin:redhat \
	  docker://docker-registry.default.svc.cluster.local:5000/${devProject}/tasks:${devTag} \
	  docker://${nexus_registry}/tasks:${devTag}"
          // TBD: Tag the built image with the production tag.
	  openshift.withCluster() {
            openshift.withProject("${prodProject}") {
              openshift.tag("${devProject}/tasks:${devTag}", "${devProject}/tasks:${prodTag}")
	    }
	  }
	}
      }

      // Blue/Green Deployment into Production
      // -------------------------------------
      def destApp   = "tasks-green"
      def activeApp = ""

      stage('Blue/Green Production Deployment') {
	script {
          // TBD: Determine which application is active
          //      Set Image, Set VERSION
          //      Deploy into the other application
          //      Make sure the application is running and ready before proceeding
	  openshift.withCluster() {
            openshift.withProject("${prodProject}") {
	      activeApp = openshift.selector("route", "tasks").object().spec.to.name
              if (activeApp == "tasks-green") {
                destApp = "tasks-blue"
              }
              echo "Active Application:      " + activeApp
              echo "Destination Application: " + destApp
	      def dc = openshift.selector("dc/${destApp}").object()
	      dc.spec.template.spec.containers[0].image="docker-registry.default.svc:5000/${devProject}/tasks:${prodTag}"
	      openshift.apply(dc)
	      openshift.selector("configmap", "${destApp}-config").delete()
	      def configmap = openshift.create("configmap", "${destApp}-config", "--from-file=./configuration/application-users.properties", "--from-file=./configuration/application-roles.properties" )
	      openshift.set("env dc/${destApp} VERSION='${prodTag} (${destApp})' -n ${GUID}-tasks-prod")
	      openshift.selector("dc", "${destApp}").rollout().latest();
	      def dc_prod = openshift.selector("dc", "${destApp}").object()
              def dc_version = dc_prod.status.latestVersion
	      def rc_prod = openshift.selector("rc", "${destApp}-${dc_version}").object()
              echo "Waiting for ${destApp} to be ready"
              while (rc_prod.spec.replicas != rc_prod.status.readyReplicas) {
            	sleep 5
            	rc_prod = openshift.selector("rc", "${destApp}-${dc_version}").object()
              }
	    }
          }
	}
      }

      stage('Switch over to new Version') {
    	echo "Switching Production application to ${destApp}."
    	script {
	  // TBD: Execute switch
      	  openshift.withCluster() {
            openshift.withProject("${prodProject}") {
              def route = openshift.selector("route/tasks").object()
              route.spec.to.name="${destApp}"
              openshift.apply(route)
            }
	  }
	}
      }

    }
  }
}

// Convenience Functions to read version from the pom.xml
// Do not change anything below this line.
// --------------------------------------------------------
def getVersionFromPom(pom) {
  def matcher = readFile(pom) =~ '<version>(.+)</version>'
  matcher ? matcher[0][1] : null
}
